### ISSUE TITLE
program.build() throws cl::BuildError containing an empty buildlog

### ISSUE THREAD

**Issue by logixoul** [KhronosGroup/OpenCL-CLHPP#125] opened 2020-12-26 10:00 UTC
More precisely, `exc.getBuildLog()` returns a length=1 vector, while `exc.getBuildLog()[0].second` equals just `"\n"`.

I am building my app with the following setup:

```
#define CL_HPP_ENABLE_EXCEPTIONS
#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#define CL_HPP_TARGET_OPENCL_VERSION 120 // the top ver supported by my nVidia gpu, i think
#include <CL/cl2.hpp>
```

My kernel string is:
```
	float2 compmul(float2 p, float2 q) {
		float a = p.x, b = p.y;
		float c = q.x, d = q.y;
		float ac = a * c;
		float bd = b * d;
		float2 out;
		out.x = ac - bd;
		out.y = (a + b) * (c + d) - ac - bd;
		return out;
	}
	void kernel compmulKernel(global const float2* A, global const float2* B, global float2* C) {
		int gid = get_global_id(0);
		C[gid] = compmul(A[gid], B[gid]);
	}
```

**Comment by MathiasMagnus** [comment] 2020-12-26 22:46
I've had a student with a similar issue on MacOS. Coupd you also show the relevant parts of your try and catch blocks?

**Comment by logixoul** [comment] 2020-12-27 13:49
@MathiasMagnus sure!

```
	std::vector<std::string> sources = { program_code };

	auto program = cl::Program(context, sources);
	try {
		program.build("-cl-std=CL1.2");
	}
	catch (cl::BuildError const& e) {
		//console() << " Error building: " << program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(m_device) << endl;
		console() << " Error building: " << endl;
		auto buildLog = e.getBuildLog();
		for (auto line : buildLog) {
			console() << "\t" << line.first.getInfo<CL_DEVICE_NAME>() << "=>" << line.second << endl;
		}
		throw std::runtime_error("");
	}

```

**Comment by bashbaug** [comment] 2021-01-05 23:29
I tried reproducing the issue using my [kernelfromfile](https://github.com/bashbaug/SimpleOpenCLSamples/tree/master/samples/05_kernelfromfile) sample and I wasn't able to reproduce it.  This admittedly isn't a complete apples-to-apples test but it's as close as I could get, and I did run on an NVIDIA GPU as hinted by the comments above.

Would it be possible to collect a CallLogging and BuildLogging trace using the [Intercept Layer for OpenCL Applications](https://github.com/intel/opencl-intercept-layer)?  I think that would be the easiest way to debug this issue since I suspect it's related to your specific device or driver version.  Thanks!

**Comment by MathiasMagnus** [comment] 2021-01-06 01:00
I was thinking of changing the compilation of the problematic kernel to naked C API and log the build error that way. That would show whether the C++ wrapper is at fault (highly doubt) or the runtime.

**Comment by logixoul** [comment] 2021-01-23 09:45
I tried with @bashbaug 's kernelfromfile sample and it doesn't have the problem. I'll try to distill the difference between my app and his sample.

**Comment by bashbaug** [comment] 2023-07-14 23:37
Hello!  We found this issue as part of a recent issue scrub and we are going to close it because it appears to be an issue with a specific driver or device.  We hope you were able to find a workaround to your problem or that updated drivers fixed it.  Thanks!

**Closed by bashbaug** 2023-07-14 23:37 UTC
