### ISSUE TITLE
Trivial example fails

### ISSUE THREAD

**Issue by planetmarshall** [KhronosGroup/OpenCL-CLHPP#186] opened 2022-12-19 15:37 UTC
Hi - I've created a fairly trivial example using the C++ API but have been unable to get it to work. Have tested on both Intel and NVIDIA ICDs - maybe someone could point out what I'm missing?

If I put a `printf` into the kernel then it works - so I was thinking there's some synchronization missing somewhere?

Thanks.

```.cpp
#define CL_HPP_ENABLE_EXCEPTIONS
#define CL_HPP_TARGET_OPENCL_VERSION 300

#include <CL/opencl.hpp>

#include <iostream>
#include <vector>

int main(int argc, char **argv)
{
    std::vector<cl::Platform> platforms;
    cl::Platform::get(&platforms);
    auto nvidia_platform = std::find_if(platforms.begin(), platforms.end(), [] (const auto & platform) {
      auto vendor = platform.template getInfo<CL_PLATFORM_NAME>();
      return vendor.find("NVIDIA") != std::string::npos;
    });

    if (nvidia_platform == platforms.end()) {
        std::cout << "No OpenCL Platform available\n";
        return 0;
    }
    auto default_platform = cl::Platform::setDefault(*nvidia_platform);
    if (default_platform() != (*nvidia_platform)()) {
        std::cerr << "Error setting default platform\n";
    }
    std::cout << "Using OpenCL Platform: " << nvidia_platform->getInfo<CL_PLATFORM_NAME>() << '\n';

    std::string kernel{R"CLC(
        kernel void set_value(global int *output)
        {
          int index = get_global_id(0);
          output[index] = 42;
        }
    )CLC"};

    std::vector<std::string> program_sources;
    program_sources.push_back(kernel);

    cl::Program program(program_sources);
    try {
        program.build("-cl-std=CL3.0");
    }
    catch (...) {
        // Print build info for all devices
        cl_int buildErr = CL_SUCCESS;
        auto buildInfo = program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(&buildErr);
        for (auto &pair : buildInfo) {
            std::cerr << pair.second << std::endl << std::endl;
        }

        return 1;
    }

    cl::coarse_svm_vector<int> output{0}
    auto kernel = cl::KernelFunctor<cl::coarse_svm_vector<int>& >(program, "set_value");

    cl_int error;
    kernel(cl::EnqueueArgs(cl::NDRange(1)), output, error);

    if (error != CL_SUCCESS) {
        std::cerr << "Error running kernel\n";
    }

    if (output[0] != 42) {
        std::cout << "Expected 42 but was " << output[0] << '\n';
    }

    return 0;
}
```

**Comment by planetmarshall** [comment] 2022-12-19 15:58
It works if instead of a `cl::coarse_svm_vector` I use a conventional vector with a `cl::Buffer`.

**Comment by bashbaug** [comment] 2023-01-04 02:36
Hello!

Your intuition was right and the issue is missing synchronization.  Since you are using a coarse-grain SVM allocation, you also need to map the coarse-grain allocation to safely read the contents on the host.  In the snippet below, the call to enqueueMapSVM both does the map and is blocking, so it takes care of synchronization as well.

Can you try something like the following?  This worked for me:

```c++
    if (error != CL_SUCCESS) {
        std::cerr << "Error running kernel\n";
    }

    // This is new - need to map coarse grain SVM to read it on the host:
    error = enqueueMapSVM(output, CL_TRUE, CL_MAP_READ);
    if (error != CL_SUCCESS) {
        std::cerr << "Error mapping SVM\n";
    }

    if (output[0] != 42) {
        std::cout << "Expected 42 but was " << output[0] << '\n';
    } else {
        std::cout << "Success!\n";
    }

    // This is also new - need to unmap coarse grain SVM before reusing it on the device:
    error = enqueueUnmapSVM(output);
    if (error != CL_SUCCESS) {
        std::cerr << "Error unmapping SVM\n";
    }
```

**Comment by bashbaug** [comment] 2023-07-14 23:46
Hello, we found this issue as part of a recent issue scrub and we are going to close it as expected behavior for your example program.  Please see the comment above for a possible solution to your problem.  Thanks!

**Closed by bashbaug** 2023-07-14 23:46 UTC
