### ISSUE TITLE
Expose retain/release functions

### ISSUE THREAD

**Issue by umar456** [KhronosGroup/OpenCL-CLHPP#97] opened 2020-06-02 19:21 UTC
Currently the retain and release functions are protected member functions of the Wrapper class. What is the reasoning behind this decision? There doesn't seem to be a way to call the retain and release functions on the C++ objects without getting the underlying OpenCL handles and calling the C API. I would be happy to create a PR if this behavior is not intentional.

**Comment by jrprice** [comment] 2020-06-09 19:36
The intent here was that the user should very rarely need to call these functions directly, because they are called automatically by the copy constructors/assignment operators. This is the recommended way of managing OpenCL object lifetimes when using the C++ API. If it's really necessary to manage the reference counts manually, you can get at the underlying C object to do so as you mention.

Do you have a particular use case where this isn't feasible?

**Comment by bashbaug** [comment] 2023-07-14 23:28
Hello, we found this issue as part of a recent bug scrub and are going to close this issue as expected behavior.  We recommend that using `operator()` to gain access to the underlying OpenCL objects if you need to explicitly call retain or release on one of the C++ objects.  Thanks!

**Closed by bashbaug** 2023-07-14 23:28 UTC
