### ISSUE TITLE
Cannot compile cl2.hpp using libc++

### ISSUE THREAD

**Issue by rickpe** [KhronosGroup/OpenCL-CLHPP#24] opened 2016-10-21 08:00 UTC
When I attempt to use the OpenCL C++ wrappers version 2.1.0 (cl2.hpp) together with CLang 3.9/3.6 and libc++ 1.0~svn199600-1 the following program does not compile. I am running Ubuntu 14.04.

```
#define CL_HPP_MINIMUM_OPENCL_VERSION 100
#define CL_HPP_TARGET_OPENCL_VERSION 110
#define CL_HPP_ENABLE_EXCEPTIONS
#include "CL/cl2.hpp"

int main(int argc, char *argv[])
{
}
```

Compiler Output:

```
$ clang++-3.9 -std=c++11 opencl.cpp -I Build/Host-Linux-Clang/Release/Thirdparty/OpenCl/include/ -lOpenCL -stdlib=libc++
In file included from opencl.cpp:8:
In file included from Build/Host-Linux-Clang/Release/Thirdparty/OpenCl/include/CL/cl2.hpp:504:
/usr/include/c++/v1/utility:253:9: error: field has incomplete type 'cl::Device'
    _T1 first;
        ^
/usr/include/c++/v1/type_traits:2023:27: note: in instantiation of template class 'std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >' requested here
                 decltype(__is_constructible_test(declval<_Tp>(), declval<_Args>()...))
                          ^
/usr/include/c++/v1/type_traits:2072:14: note: in instantiation of template class 'std::__1::__is_constructible<false, std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >,
      std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > &&>' requested here
    : public __is_constructible<is_scalar<_Tp>::value || is_reference<_Tp>::value,
             ^
/usr/include/c++/v1/type_traits:2098:14: note: in instantiation of template class 'std::__1::__is_constructible_void_check<false, std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >,
      std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > &&>' requested here
    : public __is_constructible_void_check<__contains_void<_Tp, _Args...>::value
             ^
/usr/include/c++/v1/type_traits:2578:34: note: in instantiation of template class 'std::__1::is_constructible<std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >,
      std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > &&>' requested here
    : __is_nothrow_constructible<is_constructible<_Tp, _Args...>::value, _Tp, _Args...>
                                 ^
/usr/include/c++/v1/type_traits:2713:14: note: in instantiation of template class 'std::__1::is_nothrow_constructible<std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >,
      std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > &&>' requested here
    : public is_nothrow_constructible<_Tp, typename add_rvalue_reference<_Tp>::type>
             ^
/usr/include/c++/v1/vector:575:20: note: in instantiation of template class 'std::__1::is_nothrow_move_constructible<std::__1::allocator<std::__1::pair<cl::Device, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >' requested here
        _NOEXCEPT_(is_nothrow_move_constructible<allocator_type>::value);
                   ^
Build/Host-Linux-Clang/Release/Thirdparty/OpenCl/include/CL/cl2.hpp:1905:7: note: in instantiation of exception specification for 'vector' requested here
class BuildError : public Error
      ^
Build/Host-Linux-Clang/Release/Thirdparty/OpenCl/include/CL/cl2.hpp:660:11: note: forward declaration of 'cl::Device'
    class Device;
          ^
Build/Host-Linux-Clang/Release/Thirdparty/OpenCl/include/CL/cl2.hpp:1926:19: note: implicit move constructor for 'cl::BuildError' first required here
            throw BuildError(err, errStr, buildLogs);
                  ^
1 error generated.
```

**Comment by psteinb** [comment] 2017-01-13 09:55
can you try with appending `-lc++ -lc++abi` to your compile command?

**Comment by rickpe** [comment] 2017-01-19 11:20
No this did not work. It fails already in the compilation phase. If I do not define CL_HPP_ENABLE_EXCEPTIONS it compiles okay.

**Comment by mz24cn** [comment] 2017-02-10 07:53
mingw 6.3 and msvc 2015 is okay and fail to run ... https://www.khronos.org/bugzilla/show_bug.cgi?id=1937

**Comment by Jezz0r** [comment] 2017-09-06 09:06
Are there any updates on this? I am hitting the same issue

**Comment by jrprice** [comment] 2017-10-11 09:36
I've finally got round to trying this, but I'm unable to reproduce the issue on Debian or macOS, at least with the versions of libc++ that are packaged with them.

The version that ships with Ubuntu 14.04 is pretty ancient (svn199600 - from Jan 2014), so this could just be a bug in that version of libc++. If anyone who has this issue is able to try and more recent version of libc++ to confirm that would be very useful (I don't have any old machines running Ubuntu 14.04 right now).

**Comment by soulslicer** [comment] 2018-02-21 17:47
Is this fixed?

**Comment by jrprice** [comment] 2018-02-21 18:19
> Is this fixed?

See my comment above - I can't reproduce this with recent versions of libc++, so likely to be a bug in older versions.

**Comment by jrprice** [comment] 2018-10-29 17:29
Closing as this appears to be a bug an old version of libc++, not the headers themselves. If anyone encounters this with a recent version of libc++, please open a new issue.

**Closed by jrprice** 2018-10-29 17:29 UTC
